// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.6
// source: signaller.proto

package grpc_signaller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStateChangeSignal_State int32

const (
	StreamStateChangeSignal_NOTCONNECTED StreamStateChangeSignal_State = 0
	StreamStateChangeSignal_UNRESPONSIVE StreamStateChangeSignal_State = 1
	StreamStateChangeSignal_CONNECTED    StreamStateChangeSignal_State = 2
	StreamStateChangeSignal_RUNNING      StreamStateChangeSignal_State = 3
)

// Enum value maps for StreamStateChangeSignal_State.
var (
	StreamStateChangeSignal_State_name = map[int32]string{
		0: "NOTCONNECTED",
		1: "UNRESPONSIVE",
		2: "CONNECTED",
		3: "RUNNING",
	}
	StreamStateChangeSignal_State_value = map[string]int32{
		"NOTCONNECTED": 0,
		"UNRESPONSIVE": 1,
		"CONNECTED":    2,
		"RUNNING":      3,
	}
)

func (x StreamStateChangeSignal_State) Enum() *StreamStateChangeSignal_State {
	p := new(StreamStateChangeSignal_State)
	*p = x
	return p
}

func (x StreamStateChangeSignal_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamStateChangeSignal_State) Descriptor() protoreflect.EnumDescriptor {
	return file_signaller_proto_enumTypes[0].Descriptor()
}

func (StreamStateChangeSignal_State) Type() protoreflect.EnumType {
	return &file_signaller_proto_enumTypes[0]
}

func (x StreamStateChangeSignal_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamStateChangeSignal_State.Descriptor instead.
func (StreamStateChangeSignal_State) EnumDescriptor() ([]byte, []int) {
	return file_signaller_proto_rawDescGZIP(), []int{0, 0}
}

type StreamStateChangeSignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid   uint32                        `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Oldstate StreamStateChangeSignal_State `protobuf:"varint,3,opt,name=oldstate,proto3,enum=StreamStateChangeSignal_State" json:"oldstate,omitempty"`
	Newstate StreamStateChangeSignal_State `protobuf:"varint,4,opt,name=newstate,proto3,enum=StreamStateChangeSignal_State" json:"newstate,omitempty"`
}

func (x *StreamStateChangeSignal) Reset() {
	*x = StreamStateChangeSignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signaller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamStateChangeSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStateChangeSignal) ProtoMessage() {}

func (x *StreamStateChangeSignal) ProtoReflect() protoreflect.Message {
	mi := &file_signaller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStateChangeSignal.ProtoReflect.Descriptor instead.
func (*StreamStateChangeSignal) Descriptor() ([]byte, []int) {
	return file_signaller_proto_rawDescGZIP(), []int{0}
}

func (x *StreamStateChangeSignal) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StreamStateChangeSignal) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *StreamStateChangeSignal) GetOldstate() StreamStateChangeSignal_State {
	if x != nil {
		return x.Oldstate
	}
	return StreamStateChangeSignal_NOTCONNECTED
}

func (x *StreamStateChangeSignal) GetNewstate() StreamStateChangeSignal_State {
	if x != nil {
		return x.Newstate
	}
	return StreamStateChangeSignal_NOTCONNECTED
}

type SignalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signaller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_signaller_proto_rawDescGZIP(), []int{1}
}

func (x *SignalResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_signaller_proto protoreflect.FileDescriptor

var file_signaller_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x82, 0x02, 0x0a, 0x17, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x3a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x43, 0x4f, 0x4e,
	0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x52, 0x45,
	0x53, 0x50, 0x4f, 0x4e, 0x53, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f,
	0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22, 0x20, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x55, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x17, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x1a, 0x0f,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6f,
	0x62, 0x62, 0x79, 0x2d, 0x77, 0x61, 0x6e, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_signaller_proto_rawDescOnce sync.Once
	file_signaller_proto_rawDescData = file_signaller_proto_rawDesc
)

func file_signaller_proto_rawDescGZIP() []byte {
	file_signaller_proto_rawDescOnce.Do(func() {
		file_signaller_proto_rawDescData = protoimpl.X.CompressGZIP(file_signaller_proto_rawDescData)
	})
	return file_signaller_proto_rawDescData
}

var file_signaller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signaller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signaller_proto_goTypes = []interface{}{
	(StreamStateChangeSignal_State)(0), // 0: StreamStateChangeSignal.State
	(*StreamStateChangeSignal)(nil),    // 1: StreamStateChangeSignal
	(*SignalResponse)(nil),             // 2: SignalResponse
}
var file_signaller_proto_depIdxs = []int32{
	0, // 0: StreamStateChangeSignal.oldstate:type_name -> StreamStateChangeSignal.State
	0, // 1: StreamStateChangeSignal.newstate:type_name -> StreamStateChangeSignal.State
	1, // 2: SignalService.SignalStreamStateChange:input_type -> StreamStateChangeSignal
	2, // 3: SignalService.SignalStreamStateChange:output_type -> SignalResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signaller_proto_init() }
func file_signaller_proto_init() {
	if File_signaller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_signaller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamStateChangeSignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signaller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signaller_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaller_proto_goTypes,
		DependencyIndexes: file_signaller_proto_depIdxs,
		EnumInfos:         file_signaller_proto_enumTypes,
		MessageInfos:      file_signaller_proto_msgTypes,
	}.Build()
	File_signaller_proto = out.File
	file_signaller_proto_rawDesc = nil
	file_signaller_proto_goTypes = nil
	file_signaller_proto_depIdxs = nil
}
